# Ключ проекта и организация в SonarCloud
sonar.projectKey=Michael57e_qa-auto-engineer-javascript-project-87
sonar.organization=michael57e

# Пути к исходникам и тестам
sonar.sources=src
sonar.tests=__tests__

# Включаем только JS-тесты
sonar.test.inclusions=**/*.test.js

# Исключаем node_modules
sonar.exclusions=**/node_modules/**

# Путь к отчету покрытия для JavaScript
sonar.javascript.lcov.reportPaths=coverage/lcov.info