sonar.projectKey=michael57e_qa-auto-engineer-javascript-project-87
sonar.organization=michael57e

sonar.sources=src
sonar.tests=__tests__
sonar.test.inclusions=**/*.test.js
sonar.exclusions=**/node_modules/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
